import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const db = new PGlite();
const user = '11111111-1111-4111-8111-111111111111';
const business = '22222222-2222-4222-8222-222222222222';
const recipe = '33333333-3333-4333-8333-333333333333';
const recipe2 = '44444444-4444-4444-8444-444444444444';
const order = '55555555-5555-4555-8555-555555555555';
await db.exec(`
  create role authenticated;
  create schema auth;
  create table auth.users(id uuid primary key);
  create function auth.uid() returns uuid language sql stable as 'select nullif(current_setting(''request.jwt.claim.sub'',true),'''')::uuid';
  create table businesses(id uuid primary key, user_id uuid references auth.users(id));
  create table recipes(id uuid primary key, user_id uuid, business_id uuid, name text);
  create table finished_goods_stock(recipe_id uuid primary key, qty_on_hand numeric);
  create table ingredients(id uuid primary key, name text, unit text, qty_on_hand numeric);
  create table recipe_ingredients(recipe_id uuid, ingredient_id uuid references ingredients(id), qty_used numeric);
  insert into auth.users values('${user}');
  insert into businesses values('${business}','${user}');
  insert into recipes values('${recipe}','${user}','${business}','อาหาร A'),('${recipe2}','${user}','${business}','อาหาร B');
  insert into finished_goods_stock values('${recipe}',10),('${recipe2}',0);
  select set_config('request.jwt.claim.sub','${user}',false);
`);
await db.exec(await readFile(new URL('../supabase/migrations/0008_sales.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/0016_made_to_order_recipes.sql', import.meta.url), 'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/0020_delivery_orders.sql', import.meta.url), 'utf8'));
await db.exec('grant usage on schema public,auth to authenticated; grant select,insert,update,delete on all tables in schema public to authenticated; set role authenticated;');
const items = [{ recipe_id: recipe, name: 'อาหาร A', qty: 2, price: 60, note: '' }, { recipe_id: recipe2, name: 'อาหาร B', qty: 1, price: 80, note: 'ไม่เผ็ด' }];
await db.query('insert into delivery_orders(id,business_id,channel,reference,items,due_at) values($1,$2,$3,$4,$5,now())', [order,business,'grab','G-1',JSON.stringify(items)]);
await assert.rejects(db.query('insert into delivery_orders(id,business_id,channel,reference,items,due_at) values(gen_random_uuid(),$1,$2,$3,$4,now())',[business,'grab','G-1',JSON.stringify(items)]));
await assert.rejects(db.query('select advance_delivery_order($1,$2,$3,$4)',[order,business,'new','delivered']));
for (const [from,to] of [['new','cooking'],['cooking','ready'],['ready','delivered']]) await db.query('select advance_delivery_order($1,$2,$3,$4)',[order,business,from,to]);
await assert.rejects(db.query('select advance_delivery_order($1,$2,$3,$4)',[order,business,'ready','delivered']));
const book = () => db.query('select book_delivery_order($1,$2,$3,$4)',[order,business,JSON.stringify({[recipe]:20,[recipe2]:30}),30]);
await assert.rejects(book());
assert.equal((await db.query('select count(*)::int as n from sales')).rows[0].n,0, 'failed second line rolls back first sale');
assert.equal(Number((await db.query('select qty_on_hand from finished_goods_stock where recipe_id=$1',[recipe])).rows[0].qty_on_hand),10,'stock rollback');
assert.equal((await db.query('select booked_at from delivery_orders')).rows[0].booked_at,null);
await db.exec(`reset role; update finished_goods_stock set qty_on_hand=5 where recipe_id='${recipe2}'; set role authenticated;`);
await book(); await book();
assert.equal((await db.query('select count(*)::int as n from sales')).rows[0].n,2,'retry does not duplicate sales');
assert.equal(Number((await db.query('select qty_on_hand from finished_goods_stock where recipe_id=$1',[recipe])).rows[0].qty_on_hand),8,'stock deducted once');
await assert.rejects(db.exec('delete from sales'), 'linked sale cannot be deleted');
await db.exec("update sales set payment_status='paid'");
await db.exec("select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999999',false)");
assert.equal((await db.query('select count(*)::int as n from delivery_orders')).rows[0].n,0,'other user cannot read queue');
await assert.rejects(book(),'other user cannot book');
await db.exec(`select set_config('request.jwt.claim.sub','${user}',false)`);
await db.query('insert into sales(business_id,recipe_id,qty_bottles,price_charged_total) values($1,$2,1,60)',[business,recipe]);
await db.exec('delete from sales where delivery_order_id is null');
assert.equal((await db.query('select count(*)::int as n from sales')).rows[0].n,2,'legacy sale deletion still works');
await db.exec(`reset role;
  update recipes set is_made_to_order=true where id='${recipe}';
  insert into ingredients values('${recipe}','หมู','กรัม',1000);
  insert into recipe_ingredients values('${recipe}','${recipe}',100);
  set role authenticated;`);
const mtoOrder = '66666666-6666-4666-8666-666666666666';
await db.query('insert into delivery_orders(id,business_id,channel,items,due_at) values($1,$2,$3,$4,now())',[mtoOrder,business,'self',JSON.stringify([items[0]])]);
for (const [from,to] of [['new','cooking'],['cooking','ready'],['ready','delivered']]) await db.query('select advance_delivery_order($1,$2,$3,$4)',[mtoOrder,business,from,to]);
await db.query('select book_delivery_order($1,$2,$3,0)',[mtoOrder,business,JSON.stringify({[recipe]:20})]);
assert.equal(Number((await db.query('select qty_on_hand from ingredients')).rows[0].qty_on_hand),800,'made-to-order raw stock deducted');
assert.equal(Number((await db.query('select qty_used from sale_ingredient_usage')).rows[0].qty_used),200,'raw usage snapshot saved');
await db.close();
console.log('PASS: transitions, duplicate references, rollback, idempotent booking, stock, RLS, linked-sale protection, legacy deletion');
